# Generated by Django 5.1.7 on 2025-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_img', models.CharField(max_length=255)),
                ('product_category', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('product_desc', models.CharField(max_length=255)),
            ],
        ),
    ]
